import { z } from "zod";
export const createJobPostSchema = z.object({
  jobTitle: z.number(),
  jobLocation: z.number(),
  numberOfOpenings: z.number().int().positive(),
  area: z.number(),
  experience: z.number().int().nonnegative(),
  monthlyInHand: z.string(),
  isBonusAvailable: z.boolean(),
  jobDescription: z.string(),
  skills: z.number(),
  preferredLanguage: z.string().optional(),
  age: z.string().optional(),
  certification: z.string().optional(),
  specialization: z.string().optional(),
  employmentType: z.string(),
  interviewMethod: z.string(),
  companyName: z.string(),
  sizeOfOrganisation: z.string(),
  jobAddress: z.string(),
  phoneNumber: z.string(),
  emailId: z.string().email(),
  isActive: z.boolean(),
  hrId: z.string(),
});

// Schema for updating a JobPost (all fields optional)
export const updateJobPostSchema = z.object({
  id: z.string(),
  jobTitle: z.number().optional(),
  jobLocation: z.number().optional(),
  numberOfOpenings: z.number().int().positive().optional(),
  area: z.number().optional(),
  experience: z.number().int().nonnegative().optional(),
  monthlyInHand: z.string().optional(),
  isBonusAvailable: z.boolean().optional(),
  jobDescription: z.string().optional(),
  skills: z.number().optional(),
  preferredLanguage: z.string().optional(),
  age: z.string().optional(),
  certification: z.string().optional(),
  specialization: z.string().optional(),
  employmentType: z.string().optional(),
  interviewMethod: z.string().optional(),
  companyName: z.string().optional(),
  sizeOfOrganisation: z.string().optional(),
  jobAddress: z.string().optional(),
  phoneNumber: z.string().optional(),
  emailId: z.string().email().optional(),
  isActive: z.boolean().optional(),
  hrId: z.string().optional(),
});
